version: "3"
services:
  round-tech-test:
    image: httpd:2.4
    container_name: round-tech-test
    ports:
        - 80:80
    volumes:
        - ./src/:/usr/local/apache2/htdocs/
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "10M"
            max-file: "10"